name: record_voice_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  audioplayers: ^6.1.2
  firebase_core: ^3.11.0
  firebase_storage: ^12.4.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  path_provider: ^2.1.5
  record: ^5.2.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  change_app_package_name: ^1.4.0
  custom_lint: ^0.7.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
