// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD06Wl7felwdKLPMpRC074OYy_iDKMiBa0',
    appId: '1:445297885072:android:6a1cbb5107fccbbf4dbd15',
    messagingSenderId: '445297885072',
    projectId: 'flutter-varios-a6a82',
    databaseURL: 'https://flutter-varios-a6a82-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-a6a82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqBUFV1myJGpXfijBDzVwE_ogX0EtHZGU',
    appId: '1:445297885072:ios:0d85a7971ee9c1b94dbd15',
    messagingSenderId: '445297885072',
    projectId: 'flutter-varios-a6a82',
    databaseURL: 'https://flutter-varios-a6a82-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-a6a82.firebasestorage.app',
    iosBundleId: 'com.telepatiadev.recordvoice',
  );

}